# Generated by Django 2.2.6 on 2019-11-13 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staff_id', models.CharField(max_length=10)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('b_date', models.CharField(max_length=9)),
                ('telephone', models.CharField(max_length=14)),
                ('gender', models.CharField(max_length=6)),
                ('district', models.CharField(max_length=20)),
                ('nationality', models.CharField(max_length=30)),
            ],
        ),
    ]
