# Generated by Django 2.2.6 on 2019-11-14 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Staff', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Student',
            new_name='Staff',
        ),
    ]
