# Generated by Django 2.2.6 on 2019-11-14 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='hobbies',
        ),
    ]
